;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]
margin-top    = 0
margin-bottom = 0
include-file = $HOME/.config/polybar/colors.ini

[bar/juanjo]
monitor = ${env:MONITOR}
width = 100%
height = 24pt
radius = 0
background = ${colors.base}
border-color = ${colors.sky}
border-size = 1pt
foreground=${colors.surface0}
line-size = 0
padding-left = 0
padding-right = 0
module-margin = 0
separator = |
separator-foreground = ${colors.flamingo}
font-0 = SauceCodePro Nerd Font:size=12;0
font-1 = MaterialIcons:size=10;0
font-2 = Termsynu:size=8:antialias=false;-2
font-3 = FontAwesome:size=10;0
modules-left = xworkspaces xwindow
modules-center = date spotify
modules-right = pomodoro cpu memory gpu-status battery wireless-network network bluetooth
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
tray-position = right
tray-maxsize = 16
tray-offset-y = 1

[bar/sidebar]
monitor = ${env:MONITOR}
width = 100%
height = 24pt
radius = 0
background = ${colors.base}
foreground = ${colors.overlay1}
line-size = 0
border-size = 0
border-color = #00000000
padding-left = 0
padding-right = 0
module-margin = 0
separator = |
separator-foreground = ${colors.flamingo}
font-0 = SauceCodePro Nerd Font:size=12;0
font-1 = MaterialIcons:size=10;0
font-2 = Termsynu:size=8:antialias=false;-2
font-3 = FontAwesome:size=10;0
modules-left = xworkspaces xwindow
modules-right = wlan
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/script/bluetooth.sh
interval = 2
click-left = exec blueberry
click-right = ~/.config/polybar/script/toggle_bluetooth.sh
format-padding = 0
format-foreground = #ffffff

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true
icon-0 = main;
icon-1 = www;
icon-2 = slack;
icon-3 = misc;
icon-4 = Spotify;
icon-5 = Docker;
icon-default = 

label-active = %icon%
label-active-background = ${colors.sapphire}
label-active-foreground = ${colors.surface0}
label-active-padding = 1

label-focused = %icon%
label-focused-foreground = ${colors.flamingo}
label-focused-background = ${colors.text}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-foreground = ${colors.green}
label-occupied-padding = 1
label-urgent = %icon%

label-urgent-background = ${colors.red}
label-urgent-foreground = ${colors.white}
label-urgent-overline   = ${colors.mauve}
label-urgent-underline  = ${colors.bg}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.rosewater}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%
label-foreground = ${colors.yellow}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.flamingo}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.overlay1}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.flamingo}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.overlay1}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.overlay1}
label-indicator-background = ${colors.base}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.text}
label = %percentage_used:2%%
label-foreground = ${colors.text}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.text}
label = %percentage:2%%
label-foreground = ${colors.text}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wireless-network]
type = internal/network
interface = wlp59s0
interval = 3.0
ping-interval = 10

format-connected = <ramp-signal> <label-connected>
label-connected = %essid%
label-connected-foreground = ${colors.subtext1}
label-disconnected =    not connected
label-disconnected-foreground = ${colors.red}

ramp-signal-0 = 
ramp-signal-0-foreground = ${colors.red}
ramp-signal-1 = 
ramp-signal-1-foreground = ${colors.mauve}
ramp-signal-2 = 
ramp-signal-2-foreground = ${colors.yellow}
ramp-signal-3 = 
ramp-signal-3-foreground = ${colors.peach}
ramp-signal-4 = 
ramp-signal-4-foreground = ${colors.green}
ramp-signal-padding = 1

animation-packetloss-0 = 
animation-packetloss-0-foreground = #ffa64c
animation-packetloss-1 = 
animation-packetloss-1-foreground = ${colors.red}
animation-packetloss-framerate = 500

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%
label-foreground = ${colors.text}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/mpd]
type = internal/mpd
format-online = <icon-prev> <icon-stop> <toggle> <icon-next>  <icon-repeat> <icon-random>  <bar-progress> <label-time>  <label-song>

icon-play = 
icon-pause = 
icon-stop = 
icon-prev = 
icon-next = 
icon-random = 
icon-repeat = 

toggle-on-foreground = ${colors.peach}
toggle-off-foreground = ${colors.red}

bar-progress-width = 45
bar-progress-format = %{A4:mpdseek+2: A5:mpdseek-2:}%fill%%indicator%%empty%%{A A}
bar-progress-indicator = |
bar-progress-indicator-foreground = #ff
bar-progress-indicator-font = 3
bar-progress-fill = ─
bar-progress-fill-foreground = #bb
bar-progress-fill-font = 3
bar-progress-empty = ─
bar-progress-empty-font = 3
bar-progress-empty-foreground = #44

[module/date]
type = internal/date
interval = 1
date = %a, %b %d
time = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%  %time%
label-foreground = ${colors.mauve}
label-padding-right = 1

[module/battery]
type = internal/battery
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-foreground = ${colors.sky}
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
label-discharging-foreground = ${colors.text}
label-full-foreground = ${colors.green}

ramp-capacity-0 = 
ramp-capacity-0-foreground = ${colors.red}
ramp-capacity-1 = 
ramp-capacity-1-foreground = ${colors.red}
ramp-capacity-2 = 
ramp-capacity-2-foreground = ${colors.yellow}
ramp-capacity-3 = 
ramp-capacity-3-foreground = ${colors.green}
ramp-capacity-4 = 
ramp-capacity-4-foreground = ${colors.green}
ramp-capacity-padding = 1

bar-capacity-width = 10
bar-capacity-format = %{+u}%{+o}%fill%%empty%%{-u}%{-o}
bar-capacity-fill = █
bar-capacity-fill-foreground = #ddffffff
bar-capacity-fill-font = 3
bar-capacity-empty = █
bar-capacity-empty-font = 3
bar-capacity-empty-foreground = #44ffffff

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

;[module/battery]
;type = internal/battery
;low-at = 6
;battery = BAT0
;adapter = ADP1
;poll-interval = 5
;time-format = %H:%M
;format-charging = <animation-charging> <label-charging>
;format-discharging = <ramp-capacity> <label-discharging>
;label-charging = <ramp-capacity> %percentage%%
;label-discharging = %percentage%%
;label-full = Fully charged
;label-low = BATTERY LOW
;ramp-capacity-0 = 
;ramp-capacity-1 = 
;ramp-capacity-2 = 
;ramp-capacity-3 = 
;ramp-capacity-4 = 
;bar-capacity-width = 10
;animation-charging-0 = 
;animation-charging-1 = 
;animation-charging-2 = 
;animation-charging-3 = 
;animation-charging-4 = 
;animation-charging-framerate = 750
;animation-discharging-0 = 
;animation-discharging-1 = 
;animation-discharging-2 = 
;animation-discharging-3 = 
;animation-discharging-4 = 
;animation-discharging-framerate = 500
;;animation-low-0 = !
;;animation-low-1 =
;animation-low-framerate = 200

;;;;;;;;;;;;;;
;; Power Off ;;
;;;;;;;;;;;;;;;
[module/poweroff]
type = custom/script
exec = echo " "
click-left = systemctl poweroff
click-right = i3lock-fancy -pg &
click-middle = systemctl restart

[module/gpu-status]
type = custom/script
exec = /usr/local/bin/gpu-status.sh
interval = 10
label = %output%
label-foreground = ${colors.green}

[module/pomodoro]
type = custom/script
exec = ~/.config/polybar/pomodoro/wrapper.sh
interval = 1
label = %output%
tail = true

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/spotify]
type = custom/script
exec = ~/.config/polybar/script/scroll_spotify_status.sh
label =  %output%
tail = true
format = <label>
label-foreground= ${colors.lavender}
label-padding-left=1

; vim:ft=dosini
