-- Hyprland configuration (Lua) — migrated from hyprland.conf
-- Hyprland >= 0.55 loads hyprland.lua INSTEAD of hyprland.conf (checked once at startup).
-- Docs: https://wiki.hypr.land/Configuring/Start/
--
-- The old hyprland.conf is kept as a rollback: delete/rename this file and restart
-- Hyprland to fall back to the legacy hyprlang config.

local HOME = os.getenv("HOME")

--------------------------------------------------------------------------------
-- THEME COLORS
-- The theme switcher symlinks ~/.config/themes/current.conf to a Catppuccin
-- flavor file that defines hyprlang "$name = rgb(hex)" variables. Lua can't
-- `source` hyprlang, so we parse the palette here to keep theme switching working.
--------------------------------------------------------------------------------
local function load_colors()
    -- Frappe fallback (used only if the theme file can't be read).
    local c = {
        lavender = "rgb(babbf1)",
        mauve    = "rgb(ca9ee6)",
        surface0 = "rgb(414559)",
        crust    = "rgb(232634)",
    }
    local f = io.open(HOME .. "/.config/themes/current.conf", "r")
    if f then
        local body = f:read("*a")
        f:close()
        for name, value in body:gmatch("%$([%w_]+)%s*=%s*(rgb%b())") do
            c[name] = value
        end
    end
    return c
end
local col = load_colors()

--------------------------------------------------------------------------------
-- MONITORS
-- monitors.conf is generated by nwg-displays (Super+Shift+M) in hyprlang syntax:
--   monitor=eDP-1,1920x1080@60.02,0x0,1.0
-- Parse it so nwg-displays keeps driving monitor layout after the Lua migration.
--------------------------------------------------------------------------------
local function load_monitors()
    local f = io.open(HOME .. "/.config/hypr/monitors.conf", "r")
    if not f then
        -- Fallback: let Hyprland auto-configure.
        hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
        return
    end
    local body = f:read("*a")
    f:close()
    for line in body:gmatch("[^\r\n]+") do
        -- skip comments/blank
        if not line:match("^%s*#") and line:match("%S") then
            local rest = line:match("^%s*monitor%s*=%s*(.+)$")
            if rest then
                local fields = {}
                for part in (rest .. ","):gmatch("%s*([^,]-)%s*,") do
                    fields[#fields + 1] = part
                end
                local name = fields[1] or ""
                local mode = fields[2]
                if mode == "disable" or mode == "disabled" then
                    hl.monitor({ output = name, disabled = true })
                else
                    hl.monitor({
                        output   = name,
                        mode     = mode or "preferred",
                        position = fields[3] or "auto",
                        scale    = tonumber(fields[4]) or fields[4] or "auto",
                    })
                end
            end
        end
    end
end
load_monitors()

--------------------------------------------------------------------------------
-- MY PROGRAMS
--------------------------------------------------------------------------------
local terminal    = "kitty"
local fileManager = "nautilus"
local menu        = "rofi -show drun"

--------------------------------------------------------------------------------
-- ENVIRONMENT VARIABLES
--------------------------------------------------------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

--------------------------------------------------------------------------------
-- PERMISSIONS (require a Hyprland restart to apply)
--------------------------------------------------------------------------------
hl.permission("/usr/bin/hyprshot", "screencopy", "allow")
hl.permission("/usr/bin/grim", "screencopy", "allow")
hl.permission("/usr/bin/slurp", "screencopy", "allow")

--------------------------------------------------------------------------------
-- LOOK AND FEEL
--------------------------------------------------------------------------------
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border   = { colors = { col.lavender, col.mauve }, angle = 45 },
            inactive_border = col.surface0,
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = col.crust,
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },

    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",
        follow_mouse = 1,
        follow_mouse_threshold = 3.0,
        sensitivity = 0,
        accel_profile = "adaptive",
        touchpad = {
            natural_scroll = false,
            disable_while_typing = true,
            drag_lock = false,
            middle_button_emulation = false,
        },
    },
})

-- Animation curves
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 },   { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear",         { type = "bezier", points = { { 0, 0 },      { 1, 1 } } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 },  { 0.75, 1 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 },   { 0.1, 1 } } })

hl.config({ animations = { enabled = true } })

hl.animation({ leaf = "global",           enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",           enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",          enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",             enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",           enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",     enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut",    enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",     enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3,    bezier = "easeOutQuint", style = "slidevert" })

-- Per-device config
hl.device({ name = "epic-mouse-v1", sensitivity = -0.5 })

-- Trackpad gesture (3-finger horizontal swipe changes workspace)
-- NOTE: intentionally left unconfigured in the original config; omitted here.

--------------------------------------------------------------------------------
-- SPLIT-MONITOR-WORKSPACES PLUGIN (Lua package)
-- Cloned at ~/.config/hypr/plugins/split-monitor-workspaces (release/0.56.x)
--------------------------------------------------------------------------------
package.path = package.path .. ";" .. HOME .. "/.config/hypr/plugins/split-monitor-workspaces/lua/?.lua"
local smw = require("split-monitor-workspaces")
smw.setup({
    workspace_count = 10,
    keep_focused = true,
    enable_notifications = false,
    enable_persistent_workspaces = true,
    monitor_priority = { "eDP-1", "DP-1" }, -- laptop gets the low workspace range
})

--------------------------------------------------------------------------------
-- KEYBINDINGS
--------------------------------------------------------------------------------
local mainMod = "ALT"

-- Basic application shortcuts
hl.bind(mainMod .. " + return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + CTRL + M", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("nwg-displays"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" })) -- full fullscreen
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" })) -- maximize
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("rofi -show calc -no-show-match -no-sort"))
hl.bind(mainMod .. " + semicolon", hl.dsp.exec_cmd("rofi -show emoji"))

-- Dwindle layout controls
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- Move focus (vim-style)
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))

-- Move window within the layout
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))

-- Per-monitor workspaces: switch (ALT+N) and move window (ALT+SHIFT+N)
for i = 1, smw.get_amount_of_workspaces() do
    local n = tostring(i)
    if n == "10" then n = "0" end
    hl.bind(mainMod .. " + " .. n, smw.workspace(tostring(i)))
    hl.bind(mainMod .. " + SHIFT + " .. n, smw.move_to_workspace_silent(tostring(i)))
end

-- Focus monitor directionally
hl.bind(mainMod .. " + CTRL + h", hl.dsp.focus({ monitor = "l" }))
hl.bind(mainMod .. " + CTRL + j", hl.dsp.focus({ monitor = "d" }))
hl.bind(mainMod .. " + CTRL + k", hl.dsp.focus({ monitor = "u" }))
hl.bind(mainMod .. " + CTRL + l", hl.dsp.focus({ monitor = "r" }))

-- Move window to monitor directionally
hl.bind(mainMod .. " + CTRL + SHIFT + h", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mainMod .. " + CTRL + SHIFT + j", hl.dsp.window.move({ monitor = "d" }))
hl.bind(mainMod .. " + CTRL + SHIFT + k", hl.dsp.window.move({ monitor = "u" }))
hl.bind(mainMod .. " + CTRL + SHIFT + l", hl.dsp.window.move({ monitor = "r" }))

-- Focus monitor by name
hl.bind(mainMod .. " + comma", hl.dsp.focus({ monitor = "eDP-1" }))
hl.bind(mainMod .. " + period", hl.dsp.focus({ monitor = "DP-1" }))
hl.bind(mainMod .. " + SHIFT + x", hl.dsp.workspace.swap_monitors({ monitor1 = "eDP-1", monitor2 = "DP-1" }))

-- Workspace back-and-forth
hl.bind(mainMod .. " + tab", hl.dsp.focus({ workspace = "previous" }))

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mouse drag
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- System shortcuts
hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(HOME .. "/.config/hypr/change_wallpaper.sh"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd(HOME .. "/.config/waybar/scripts/audio-device-cycle.sh"))

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region --freeze"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("hyprshot -m output -m active"))

-- Multimedia keys (locked = works on lockscreen, repeating for volume/brightness)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && " .. HOME .. "/.local/bin/volume_notify"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && " .. HOME .. "/.local/bin/volume_notify"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && " .. HOME .. "/.local/bin/volume_notify"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+ && " .. HOME .. "/.local/bin/brightness_notify"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%- && " .. HOME .. "/.local/bin/brightness_notify"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------------------------------------------------------
-- RESIZE SUBMAP (ALT+R to enter, ESC/Return to exit)
--------------------------------------------------------------------------------
hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    -- Resize with vim keys (relative pixel deltas, repeating on hold)
    hl.bind("h", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
    hl.bind("l", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
    hl.bind("k", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })
    hl.bind("SHIFT + h", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + l", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + k", hl.dsp.window.resize({ x = 0, y = -100, relative = true }), { repeating = true })
    hl.bind("SHIFT + j", hl.dsp.window.resize({ x = 0, y = 100, relative = true }), { repeating = true })
    -- Preset split ratios
    hl.bind("1", hl.dsp.exec_cmd(HOME .. "/.config/hypr/set-split-ratio.sh 0.25"))
    hl.bind("2", hl.dsp.exec_cmd(HOME .. "/.config/hypr/set-split-ratio.sh 0.33"))
    hl.bind("3", hl.dsp.exec_cmd(HOME .. "/.config/hypr/set-split-ratio.sh 0.5"))
    hl.bind("4", hl.dsp.exec_cmd(HOME .. "/.config/hypr/set-split-ratio.sh 0.67"))
    hl.bind("5", hl.dsp.exec_cmd(HOME .. "/.config/hypr/set-split-ratio.sh 0.75"))
    -- Exit resize mode
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("return", hl.dsp.submap("reset"))
end)

--------------------------------------------------------------------------------
-- WINDOW RULES
--------------------------------------------------------------------------------
-- Firefox Picture-in-Picture
hl.window_rule({ match = { class = "firefox", title = "Picture-in-Picture" }, float = true })
hl.window_rule({ match = { class = "firefox", title = "Picture-in-Picture" }, pin = true })
hl.window_rule({ match = { class = "firefox", title = "Picture-in-Picture" }, size = { 800, 450 } })

-- Common floating apps
hl.window_rule({ match = { class = "pavucontrol" }, float = true })
hl.window_rule({ match = { class = "pavucontrol" }, size = { 600, 400 } })
hl.window_rule({ match = { class = "blueman-manager" }, float = true })
hl.window_rule({ match = { class = "blueman-manager" }, size = { 700, 500 } })
hl.window_rule({ match = { class = "nm-connection-editor" }, float = true })
hl.window_rule({ match = { class = "file-roller" }, float = true })

-- Force Sweet Home 3D main window to tile
hl.window_rule({ match = { class = "com-eteks-sweethome3d-SweetHome3D", title = "Sweet Home 3D" }, tile = true })

-- File dialogs
hl.window_rule({ match = { title = "Open File" }, float = true })
hl.window_rule({ match = { title = "Save File" }, float = true })
hl.window_rule({ match = { title = "Save As" }, float = true })
hl.window_rule({ match = { title = "Open File" }, size = { 800, 600 } })
hl.window_rule({ match = { title = "Save File" }, size = { 800, 600 } })
hl.window_rule({ match = { title = "Save As" }, size = { 800, 600 } })

-- Ignore maximize requests from all apps
hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })

--------------------------------------------------------------------------------
-- AUTOSTART
--------------------------------------------------------------------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor catppuccin-mocha-dark-cursors 24")
    hl.exec_cmd(HOME .. "/.config/hypr/generate_hyprpaper_config.sh")
    hl.exec_cmd(HOME .. "/.config/hypr/monitor_change_handler.sh &")
    hl.exec_cmd("waybar & swaync & hypridle")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
end)
