local o = vim.o
local wo = vim.wo

o.shell = "/bin/sh"
o.expandtab = true
o.shiftwidth = 4
o.hidden = true
o.signcolumn = 'yes:2'
o.relativenumber = true
o.number = true
o.termguicolors = true
o.guicursor = ''
o.undofile = true
o.spell = true
o.title = true
o.ignorecase = true
o.smartcase = true
o.wildmode = 'longest:full,full'
o.list = true
o.listchars = 'trail:·'
o.mouse = 'a'
o.scrolloff = 8 
o.sidescrolloff = 8
o.joinspaces = false
o.splitright = true
o.clipboard = 'unnamedplus'
o.confirm = true
o.exrc = true
o.backup = true
o.backupdir = '~/.local/share/nvim/backup//'
o.updatetime = 300
o.redrawtime = 10000
