return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "modern",
    delay = 500,
    icons = {
      mappings = true,
      keys = {
        Up = "󰁝 ",
        Down = "󰁅 ",
        Left = "󰁍 ",
        Right = "󰁔 ",
        C = "󰘴 ",
        M = "󰘵 ",
        D = "󰘳 ",
        S = "󰘶 ",
        CR = "󰌑 ",
        Esc = "󱊷 ",
        ScrollWheelDown = "󱕐 ",
        ScrollWheelUp = "󱕑 ",
        NL = "󰌑 ",
        BS = "󰁮",
        Space = "󱁐 ",
        Tab = "󰌒 ",
        F1 = "󱊫",
        F2 = "󱊬",
        F3 = "󱊭",
        F4 = "󱊮",
      },
    },
    spec = {
      { "<leader>a", group = "Alternate (TDD)" },
      { "<leader>b", group = "Buffers" },
      { "<leader>c", group = "Code/AI" },
      { "<leader>d", group = "Debug (DAP)" },
      { "<leader>f", group = "Find" },
      { "<leader>g", group = "Git/Grep" },
      { "<leader>h", group = "Harpoon" },
      { "<leader>n", group = "NvimTree/Noice/Notify" },
      { "<leader>nm", desc = "Message History (Noice)" },
      { "<leader>nl", desc = "Last Message (Noice)" },
      { "<leader>nd", desc = "Dismiss Notifications" },
      { "<leader>ne", desc = "Error Messages (Noice)" },
      { "<leader>nh", desc = "Notification History (nvim-notify)" },
      { "<leader>o", group = "Octo/Obsidian" },
      { "<leader>op", group = "Octo: Pull Requests" },
      { "<leader>oi", group = "Octo: Issues" },
      { "<leader>oo", desc = "Obsidian: Today's daily note" },
      { "<leader>oy", desc = "Obsidian: Yesterday's note" },
      { "<leader>os", desc = "Obsidian: Search notes" },
      { "<leader>oq", desc = "Obsidian: Quick switch" },
      { "<leader>ob", desc = "Obsidian: Backlinks" },
      { "<leader>on", desc = "Obsidian: New note" },
      { "<leader>of", desc = "Obsidian: Follow link" },
      { "<leader>od", desc = "Obsidian: Toggle checkbox" },
      { "<leader>s", group = "Search" },
      { "<leader>t", group = "Test (Neotest)" },
      { "<leader>tt", group = "Trouble" },
      { "<leader>v", group = "Vim Config" },
      { "<leader>w", group = "Workspace" },
      { "<leader>x", group = "Diagnostics" },
    },
  },
  keys = {
    {
      "<leader>?",
      function()
        require("which-key").show({ global = false })
      end,
      desc = "Buffer keymaps (which-key)",
    },
  },
}
